"""Tests for generate-reviews-index.py — the reviews-index regenerator.

Every lane builds a miniature repo root under a temporary directory and drives
the CLI there. NOTHING reads the live `bionic/` tree: the refusals are
properties of the CODE, not of this repo's content, and a test that read the
live tree would false-fail when `sync.sh` runs this suite against the
crux-only staged artifact (which carries no `bionic/`).

Stdlib only. Run:
  uv run python3 -m unittest discover -s crux/scripts/tests -p 'test_generate_reviews_index.py'
"""

from __future__ import annotations

import importlib.util
import json
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

SCRIPT = Path(__file__).resolve().parent.parent / "generate-reviews-index.py"

EMPTY_INDEX = """# Decision reviews

<!-- Generated by crux/scripts/generate-reviews-index.py — do not hand-edit. -->

One row per `review-decisions` pass, newest first. Each dated report is hand-kept; this index is derived from the reports in this directory.

| date | findings | dismissed | report |
|------|----------|-----------|--------|

Reports: 0
"""


def _report(date: str, findings: list[str], dismissed: list[str]) -> str:
    block = ("dismissed: []" if not dismissed
             else "dismissed:\n" + "".join(f'  - "{d}"\n' for d in dismissed).rstrip())
    body = "\n".join(f"### Finding `{f}`\n\nSomething about a decision.\n" for f in findings)
    return f"---\ntype: adr-review\ndate: {date}\n{block}\n---\n\n# Review {date}\n\n{body}"


class ReviewsIndexTestCase(unittest.TestCase):
    def setUp(self) -> None:
        self._tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self._tmp.cleanup)
        self.root = Path(self._tmp.name)
        (self.root / ".bionic.yml").write_text(
            'config_version: "1"\ndocs_dir: bionic\n', encoding="utf-8")
        self.reviews = self.root / "bionic" / "adrs" / "reviews"
        self.reviews.mkdir(parents=True)

    def run_cli(self, *args: str) -> subprocess.CompletedProcess:
        return subprocess.run(
            [sys.executable, str(SCRIPT), "--repo-root", str(self.root), *args],
            capture_output=True, text=True)

    def write(self, name: str, text: str) -> None:
        (self.reviews / name).write_text(text, encoding="utf-8")

    # ── happy path ──────────────────────────────────────────────────────────

    def test_an_empty_directory_writes_the_zero_report_form(self):
        result = self.run_cli()
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(json.loads(result.stdout)["written"],
                         str(Path("bionic/adrs/reviews/index.md")))
        self.assertEqual((self.reviews / "index.md").read_text(encoding="utf-8"), EMPTY_INDEX)

    def test_reports_render_newest_first_with_unique_finding_counts(self):
        # The 2026-09-07 body names three ids, one of them twice — two rows of
        # the same id are one finding.
        self.write("2026-09-07.md", _report(
            "2026-09-07", ["adr-review-stale-gate", "adr-review-unused-rule",
                           "adr-review-stale-gate", "adr-review-orphan-objective"], []))
        self.write("2026-08-01.md", _report(
            "2026-08-01", ["adr-review-one"], ["ADR-0042", "ADR-0043"]))
        self.assertEqual(self.run_cli().returncode, 0)
        body = (self.reviews / "index.md").read_text(encoding="utf-8")
        self.assertIn("| 2026-09-07 | 3 | 0 | [2026-09-07.md](./2026-09-07.md) |", body)
        self.assertIn("| 2026-08-01 | 1 | 2 | [2026-08-01.md](./2026-08-01.md) |", body)
        self.assertLess(body.index("2026-09-07.md"), body.index("2026-08-01.md"))
        self.assertTrue(body.endswith("\nReports: 2\n"))
        # A positive control for the byte-stability claim: a second run over an
        # unchanged corpus is a clean gate, not drift.
        self.assertEqual(self.run_cli("--dry-run").returncode, 0)

    def test_a_flow_style_dismissed_list_counts_its_items(self):
        self.write("2026-09-07.md",
                   '---\ntype: adr-review\ndate: 2026-09-07\n'
                   'dismissed: ["ADR-0001", "ADR-0002", "ADR-0003"]\n---\n\nbody\n')
        self.assertEqual(self.run_cli().returncode, 0)
        self.assertIn("| 2026-09-07 | 0 | 3 |",
                      (self.reviews / "index.md").read_text(encoding="utf-8"))

    def test_a_stale_index_is_drift_in_dry_run_and_rebuilt_in_write_mode(self):
        self.write("2026-09-07.md", _report("2026-09-07", ["adr-review-x"], []))
        self.write("index.md", EMPTY_INDEX)
        result = self.run_cli("--dry-run")
        self.assertEqual(result.returncode, 1, result.stdout)
        self.assertTrue(json.loads(result.stdout)["drift"])
        self.assertEqual(self.run_cli().returncode, 0)
        self.assertEqual(self.run_cli("--dry-run").returncode, 0)

    # ── refusals: both modes, exit 1 + validation_errors, message on stderr ──
    #
    # A hand-edited report is a DOCUMENT finding, so the refusal takes the
    # exit-1 `validation_errors` lane `check-drift` reads as BROKEN, never the
    # exit-2 lane it reads as CRASH. The exit code alone cannot tell a
    # validation refusal from an orphan-row drift, so every assertion below
    # pins the `validation_errors` payload as its content discriminator.

    def _assert_refused(self, fragment: str) -> None:
        for args in ((), ("--dry-run",)):
            result = self.run_cli(*args)
            self.assertEqual(result.returncode, 1, f"{args}: {result.stdout}")
            payload = json.loads(result.stdout)
            errors = payload["validation_errors"]
            self.assertEqual(len(errors), 1, errors)
            self.assertIn(fragment, errors[0]["error"])
            self.assertTrue(errors[0]["file"].endswith(".md"), errors)
            self.assertIn(fragment, result.stderr)

    def test_a_refusal_leaves_the_index_unwritten(self):
        """The write mode refuses rather than emitting a half-described index."""
        self.write("notes.md", _report("2026-09-07", [], []))
        result = self.run_cli()
        self.assertEqual(result.returncode, 1, result.stdout)
        payload = json.loads(result.stdout)
        # The content discriminator: exit 1 is also the orphan-row drift lane,
        # so the code alone cannot say which refusal fired. Pin the message.
        self.assertIn("outside the reviews grammar",
                      payload["validation_errors"][0]["error"])
        self.assertIsNone(payload["written"])
        self.assertFalse((self.reviews / "index.md").exists())

    def test_a_clean_corpus_carries_no_validation_errors_key(self):
        """Positive control: the discriminator is absent on a describable corpus."""
        self.write("2026-09-07.md", _report("2026-09-07", ["adr-review-x"], []))
        result = self.run_cli("--dry-run")
        self.assertNotIn("validation_errors", json.loads(result.stdout))

    def test_a_filename_outside_the_grammar_is_refused(self):
        self.write("notes.md", _report("2026-09-07", [], []))
        self._assert_refused("outside the reviews grammar")

    def test_a_digit_shaped_non_calendar_date_is_refused(self):
        self.write("2026-02-30.md", _report("2026-02-30", [], []))
        self._assert_refused("is not a calendar date")

    def test_missing_frontmatter_is_refused(self):
        self.write("2026-09-07.md", "# Review\n\nno frontmatter here\n")
        self._assert_refused("no frontmatter block")

    def test_the_wrong_type_is_refused(self):
        self.write("2026-09-07.md",
                   "---\ntype: adr\ndate: 2026-09-07\ndismissed: []\n---\n\nbody\n")
        self._assert_refused("expected 'adr-review'")

    def test_a_future_dated_report_is_refused(self):
        # A future-dated report would anchor every cadence check on a date
        # that never arrives and suppress the nudge indefinitely.
        self.write("2999-01-01.md", _report("2999-01-01", [], []))
        self._assert_refused("is in the future")

    def test_the_today_flag_is_the_clock_the_future_check_reads(self):
        # Positive control: the same file is accepted when the clock says so,
        # which proves the refusal above turns on the date and not the name.
        self.write("2999-01-01.md", _report("2999-01-01", ["adr-review-x"], []))
        result = self.run_cli("--dry-run", "--today", "2999-01-01")
        self.assertEqual(result.returncode, 1, result.stdout)  # drift: no index yet
        payload = json.loads(result.stdout)
        self.assertNotIn("validation_errors", payload)
        self.assertTrue(payload["drift"])

    def test_a_malformed_today_flag_is_an_environment_error(self):
        result = self.run_cli("--dry-run", "--today", "not-a-date")
        self.assertEqual(result.returncode, 2, result.stdout)
        self.assertEqual(result.stdout, "")
        self.assertIn("--today", result.stderr)

    def test_a_date_disagreeing_with_the_filename_is_refused(self):
        self.write("2026-09-07.md", _report("2026-09-06", [], []))
        self._assert_refused("but the filename says")

    def test_a_missing_reviews_directory_reports_surface_absent_not_a_clean_gate(self):
        """A tree that never ran a review has no derived artifact to drift.

        Both modes exit 0 and set the `surface_absent` discriminator. The
        assertion that matters is the DISCRIMINATOR, not the exit code — a
        gate reading the code alone could not tell this from a measured pass,
        which is the false-green shape `check-drift` has to avoid downstream.
        """
        for entry in self.reviews.iterdir():
            entry.unlink()
        self.reviews.rmdir()
        for args in ((), ("--dry-run",)):
            with self.subTest(args=args):
                result = self.run_cli(*args)
                self.assertEqual(result.returncode, 0, result.stderr)
                payload = json.loads(result.stdout)
                self.assertIs(payload["surface_absent"], True)
        # Positive control: with the surface PRESENT the discriminator is
        # absent, so the assertion above distinguishes the two states.
        self.reviews.mkdir(parents=True)
        control = json.loads(self.run_cli("--dry-run").stdout)
        self.assertNotIn("surface_absent", control)
        self.assertIs(control["drift"], True)

    def test_a_zero_config_legacy_docs_tree_is_not_reported_absent(self):
        """A `docs/` tree with no .bionic.yml resolves by discovery, per §14.1."""
        (self.root / ".bionic.yml").unlink()
        shutil.rmtree(self.root / "bionic")
        legacy = self.root / "docs"
        (legacy / "adrs" / "reviews").mkdir(parents=True)
        (legacy / "manifest.yml").write_text(
            'schema_version: "5"\nconcerns_enabled: [adrs]\n', encoding="utf-8")
        payload = json.loads(self.run_cli("--dry-run").stdout)
        self.assertNotIn("surface_absent", payload)
        self.assertEqual(payload["path"], "docs/adrs/reviews/index.md")

    def test_a_dotfile_is_skipped_rather_than_refused(self):
        self.write(".DS_Store", "\x00binary junk")
        result = self.run_cli()
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual((self.reviews / "index.md").read_text(encoding="utf-8"), EMPTY_INDEX)

    # ── orphan rows ─────────────────────────────────────────────────────────

    def test_an_orphan_row_is_dry_run_drift_and_write_mode_removes_it(self):
        self.write("2026-09-07.md", _report("2026-09-07", ["adr-review-x"], []))
        self.assertEqual(self.run_cli().returncode, 0)
        stale = (self.reviews / "index.md").read_text(encoding="utf-8").replace(
            "\nReports: 1\n",
            "| 2026-06-01 | 9 | 0 | [2026-06-01.md](./2026-06-01.md) |\n\nReports: 2\n")
        # The orphan row sits inside the table, above the blank line.
        self.write("index.md", stale.replace(
            "| 2026-09-07 | 1 | 0 | [2026-09-07.md](./2026-09-07.md) |\n\n",
            "| 2026-09-07 | 1 | 0 | [2026-09-07.md](./2026-09-07.md) |\n"))
        result = self.run_cli("--dry-run")
        self.assertEqual(result.returncode, 1, result.stdout)
        payload = json.loads(result.stdout)
        self.assertTrue(payload["drift"])
        self.assertEqual(payload["orphan_rows"], ["2026-06-01.md"])
        self.assertEqual(self.run_cli().returncode, 0)
        rebuilt = (self.reviews / "index.md").read_text(encoding="utf-8")
        self.assertNotIn("2026-06-01", rebuilt)
        self.assertEqual(json.loads(self.run_cli("--dry-run").stdout)["orphan_rows"], [])


class RedactionRoutingTestCase(ReviewsIndexTestCase):
    """The CALL sites, not the function — `rule:mined-values-fenced-and-bounded`.

    A review report is hand-kept and, downstream, a pull request can ADD one;
    CI runs `check-drift` on pull requests, so this regenerator reads an
    attacker-controlled file and quotes it back onto two channels — the
    `validation_errors` array on stdout and one line on stderr. `redact` was
    already proved by `test_untrusted.py`; that it is CALLED here was proved by
    nothing, and neutering `redact` to an identity render left this file green.

    Each case asserts the bound or the replacement FIRED on a hostile value and,
    in the same case, that it did NOT fire on a legitimate one. Payloads are
    BUILT from `chr(27)` and string multiplication, never pasted: 200 filler
    characters crosses `untrusted.LIMIT` (120) while keeping every path
    component inside the 255-byte POSIX ceiling.
    """

    FILLER = 200

    def test_an_over_long_type_is_bounded_on_both_channels(self):
        hostile = "x" * self.FILLER
        self.write("2026-09-07.md",
                   f"---\ntype: {hostile}\ndate: 2026-09-07\ndismissed: []\n---\n\nbody\n")
        result = self.run_cli()
        self.assertEqual(result.returncode, 1, result.stdout)
        error = json.loads(result.stdout)["validation_errors"][0]["error"]
        # Content discriminator: this is the `type` refusal, not another.
        self.assertIn("expected 'adr-review'", error)
        # The bound fired on BOTH channels, and neither carries the payload.
        # The ceiling is on what the PAYLOAD contributed, not on the whole
        # line: stderr also carries the tool prefix, the path, and the
        # refusal's own prose, all of which this project authored.
        for channel, text in (("stdout", error), ("stderr", result.stderr)):
            with self.subTest(channel=channel):
                self.assertIn(f"truncated from {self.FILLER} characters", text)
                self.assertNotIn(hostile, text)
                self.assertNotIn("x" * (self.FILLER - 1), text)

        # PAIRED POSITIVE CONTROL: a short wrong `type` round-trips verbatim
        # with no note, so the assertions above measure the bound firing
        # rather than the message having stopped naming the value.
        self.write("2026-09-07.md",
                   "---\ntype: adr\ndate: 2026-09-07\ndismissed: []\n---\n\nbody\n")
        control = self.run_cli()
        control_error = json.loads(control.stdout)["validation_errors"][0]["error"]
        self.assertIn("frontmatter `type` is 'adr'", control_error)
        self.assertNotIn("truncated from", control_error)
        self.assertNotIn("redacted", control_error)

    def test_a_newline_in_a_report_filename_cannot_forge_a_stderr_line(self):
        # A newline is legal in a POSIX filename. Unredacted it split the
        # one-line stderr contract in two, and the second line is entirely
        # attacker-chosen text.
        hostile = "2026-09-07.md\ngenerate-reviews-index: all clear"
        (self.reviews / hostile).write_text(_report("2026-09-07", [], []),
                                            encoding="utf-8")
        result = self.run_cli()
        self.assertEqual(result.returncode, 1, result.stdout)
        # Structure: exactly one line on stderr, whatever the name contained.
        self.assertEqual(result.stderr.count("\n"), 1, repr(result.stderr))
        self.assertNotIn("all clear\n", result.stderr)
        self.assertIn("1 unprintable character redacted", result.stderr)
        # And the same value is bounded in the JSON key it also reaches.
        entry = json.loads(result.stdout)["validation_errors"][0]
        self.assertNotIn("\n", entry["file"])
        self.assertIn("\ufffd", entry["file"])

        # PAIRED POSITIVE CONTROL: a legitimate name reaches the same key
        # verbatim and produces the same one-line stderr with no note.
        (self.reviews / hostile).unlink()
        self.write("notes.md", _report("2026-09-07", [], []))
        control = self.run_cli()
        self.assertEqual(control.returncode, 1, control.stdout)
        self.assertEqual(control.stderr.count("\n"), 1, repr(control.stderr))
        self.assertEqual(json.loads(control.stdout)["validation_errors"][0]["file"],
                         "bionic/adrs/reviews/notes.md")
        self.assertNotIn("redacted", control.stderr)

    def test_an_over_long_orphan_row_link_is_bounded_in_the_envelope(self):
        # An orphan row's link text is hand-editable index content that
        # reaches the `orphan_rows` array. It is the third channel, and the
        # one a reader is least likely to think of as untrusted.
        hostile = "y" * self.FILLER + ".md"
        self.write("index.md",
                   "\n".join(EMPTY_INDEX.splitlines()[:8])
                   + f"\n| 2026-06-01 | 9 | 0 | [{hostile}](./{hostile}) |\n\nReports: 1\n")
        payload = json.loads(self.run_cli("--dry-run").stdout)
        self.assertEqual(len(payload["orphan_rows"]), 1)
        row = payload["orphan_rows"][0]
        self.assertIn(f"truncated from {len(hostile)} characters", row)
        self.assertNotIn(hostile, row)

        # PAIRED POSITIVE CONTROL: a legitimate orphan name round-trips whole,
        # which the existing orphan-row case also relies on.
        self.write("index.md",
                   "\n".join(EMPTY_INDEX.splitlines()[:8])
                   + "\n| 2026-06-01 | 9 | 0 | [2026-06-01.md](./2026-06-01.md) |\n\nReports: 1\n")
        control = json.loads(self.run_cli("--dry-run").stdout)
        self.assertEqual(control["orphan_rows"], ["2026-06-01.md"])


class ContainmentTestCase(ReviewsIndexTestCase):
    """[SECURITY:S5] No read and no write leaves the resolved `<docs_dir>`.

    ADR-0101 requirement 5 asks that "the resolved write path is
    containment-checked under the resolved `<docs_dir>`". The unguarded
    `path.write_text` this replaced followed a symlink and overwrote a file
    outside the repository at exit 0 — the write succeeded, the JSON said
    `written`, and nothing anywhere said otherwise.

    Every case pairs the refusal with a control that performs the SAME
    operation on a real file and succeeds, so "refused" cannot be satisfied by
    a script that refuses everything.
    """

    def _outside(self) -> Path:
        """A file outside the repo root, with a witness string in it."""
        tmp = tempfile.TemporaryDirectory()
        self.addCleanup(tmp.cleanup)
        victim = Path(tmp.name) / "victim.md"
        victim.write_text("UNTOUCHED\n", encoding="utf-8")
        return victim

    def test_a_symlinked_index_target_is_refused_and_the_victim_survives(self):
        """The demonstrated exploit: exit 0, and a file outside the repo overwritten.

        The refusal lands in the WALK rather than in the writer — `collect`
        checks every entry, `index.md` included, before `build` reads it back
        for the orphan-row scan. So this is exit 1 with a validation error, not
        the writer's exit 2; `_atomic_write_text`'s own leaf check stays as the
        backstop for the window between the walk and the write, and is
        exercised directly by `AtomicWriteBackstopTestCase` below.
        """
        victim = self._outside()
        (self.reviews / "index.md").symlink_to(victim)
        result = self.run_cli()
        self.assertEqual(result.returncode, 1, result.stdout)
        self.assertEqual(victim.read_text(encoding="utf-8"), "UNTOUCHED\n")
        self.assertIn("is a symlink",
                      json.loads(result.stdout)["validation_errors"][0]["error"])
        self.assertIsNone(json.loads(result.stdout)["written"])

        # PAIRED POSITIVE CONTROL: the identical write to a REAL index.md
        # succeeds, so the refusal is the symlink and not a broken writer.
        (self.reviews / "index.md").unlink()
        control = self.run_cli()
        self.assertEqual(control.returncode, 0, control.stderr)
        self.assertEqual((self.reviews / "index.md").read_text(encoding="utf-8"),
                         EMPTY_INDEX)

    def test_a_symlinked_report_entry_is_refused_rather_than_read(self):
        victim = self._outside()
        (self.reviews / "2026-09-07.md").symlink_to(victim)
        result = self.run_cli("--dry-run")
        self.assertEqual(result.returncode, 1, result.stdout)
        error = json.loads(result.stdout)["validation_errors"][0]["error"]
        # Content discriminator: the symlink refusal, not the frontmatter one
        # the victim's contents would have produced had it been read.
        self.assertIn("is a symlink", error)
        self.assertNotIn("no frontmatter block", error)

        # PAIRED POSITIVE CONTROL: a real file at the same name is read and
        # described, so the refusal is the link and not the name.
        (self.reviews / "2026-09-07.md").unlink()
        self.write("2026-09-07.md", _report("2026-09-07", ["adr-review-x"], []))
        self.assertEqual(self.run_cli().returncode, 0)
        self.assertIn("| 2026-09-07 | 1 | 0 |",
                      (self.reviews / "index.md").read_text(encoding="utf-8"))

    def test_a_symlinked_reviews_directory_is_refused_rather_than_walked(self):
        tmp = tempfile.TemporaryDirectory()
        self.addCleanup(tmp.cleanup)
        elsewhere = Path(tmp.name) / "elsewhere"
        elsewhere.mkdir()
        (elsewhere / "2026-01-01.md").write_text(_report("2026-01-01", [], []),
                                                 encoding="utf-8")
        self.reviews.rmdir()
        self.reviews.symlink_to(elsewhere, target_is_directory=True)
        result = self.run_cli("--dry-run")
        self.assertEqual(result.returncode, 2, result.stdout)
        self.assertIn("not contained under", result.stderr)

        # PAIRED POSITIVE CONTROL: the same directory contents inside the tree
        # are walked and described, so the refusal is containment and not the
        # corpus.
        self.reviews.unlink()
        shutil.copytree(elsewhere, self.reviews)
        control = self.run_cli("--dry-run")
        self.assertEqual(control.returncode, 1, control.stdout)
        self.assertIs(json.loads(control.stdout)["drift"], True)

    def test_a_symlinked_tree_directory_lands_in_the_environment_lane(self):
        """`bionic_config` owns the tree dir; this asserts the exit LANE.

        The refusal itself is `load_config`'s and is not repeated in this
        script. What was wrong is where it surfaced: `_tree_name` was called
        outside `main`'s try, so `BionicConfigError` escaped as an uncaught
        traceback — exit 1 with EMPTY stdout, which is neither the documented
        drift lane (exit 1 with JSON) nor the documented crash lane (exit 2).
        `check-drift` reads an unparseable stdout at exit 1 as a broken gate of
        unknown kind.
        """
        tmp = tempfile.TemporaryDirectory()
        self.addCleanup(tmp.cleanup)
        elsewhere = Path(tmp.name) / "elsewhere"
        (elsewhere / "adrs" / "reviews").mkdir(parents=True)
        shutil.rmtree(self.root / "bionic")
        (self.root / "bionic").symlink_to(elsewhere, target_is_directory=True)
        result = self.run_cli("--dry-run")
        self.assertEqual(result.returncode, 2, result.stdout)
        self.assertEqual(result.stdout, "")
        self.assertIn("not a proper subdirectory of the repo root", result.stderr)
        self.assertNotIn("Traceback", result.stderr)

        # PAIRED POSITIVE CONTROL: the identical layout as a real directory
        # inside the root is measured and reads clean-with-drift.
        (self.root / "bionic").unlink()
        shutil.copytree(elsewhere, self.root / "bionic")
        control = self.run_cli("--dry-run")
        self.assertEqual(control.returncode, 1, control.stdout)
        self.assertIs(json.loads(control.stdout)["drift"], True)


class AtomicWriteBackstopTestCase(unittest.TestCase):
    """`_atomic_write_text`'s own guards, which the walk preempts on the CLI.

    Driven directly BECAUSE they are a backstop: `collect` refuses a symlinked
    entry and `_contained` refuses a symlinked directory, so no CLI input
    reaches these checks in one pass. They cover the window between the walk
    and the write. The CLI-reachable refusals are asserted by
    `ContainmentTestCase` above, so this class is not the file's only coverage
    of the guard.
    """

    def setUp(self) -> None:
        spec = importlib.util.spec_from_file_location("_reviews_index", SCRIPT)
        self.mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(self.mod)
        self._tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self._tmp.cleanup)
        self.tree = Path(self._tmp.name) / "tree"
        self.tree.mkdir()

    def test_a_symlinked_target_is_refused_and_the_victim_survives(self):
        victim = Path(self._tmp.name) / "victim.md"
        victim.write_text("UNTOUCHED\n", encoding="utf-8")
        target = self.tree / "index.md"
        target.symlink_to(victim)
        with self.assertRaises(OSError) as caught:
            self.mod._atomic_write_text(target, "NEW\n", contained_under=self.tree)
        self.assertIn("is a symlink", str(caught.exception))
        self.assertEqual(victim.read_text(encoding="utf-8"), "UNTOUCHED\n")

        # PAIRED POSITIVE CONTROL: the same call to a real path writes.
        target.unlink()
        self.mod._atomic_write_text(target, "NEW\n", contained_under=self.tree)
        self.assertEqual(target.read_text(encoding="utf-8"), "NEW\n")

    def test_a_parent_resolving_outside_the_tree_is_refused(self):
        outside = Path(self._tmp.name) / "outside"
        outside.mkdir()
        link = self.tree / "linked"
        link.symlink_to(outside, target_is_directory=True)
        with self.assertRaises(OSError) as caught:
            self.mod._atomic_write_text(link / "index.md", "NEW\n",
                                        contained_under=self.tree)
        self.assertIn("not contained under", str(caught.exception))
        self.assertFalse((outside / "index.md").exists())

        # PAIRED POSITIVE CONTROL: a real subdirectory of the tree writes.
        real = self.tree / "real"
        real.mkdir()
        self.mod._atomic_write_text(real / "index.md", "NEW\n",
                                    contained_under=self.tree)
        self.assertEqual((real / "index.md").read_text(encoding="utf-8"), "NEW\n")

    def test_a_left_over_temporary_file_is_refused_rather_than_clobbered(self):
        target = self.tree / "index.md"
        (self.tree / "index.md.tmp").write_text("SOMEONE ELSE\n", encoding="utf-8")
        with self.assertRaises(OSError) as caught:
            self.mod._atomic_write_text(target, "NEW\n", contained_under=self.tree)
        self.assertIn("already exists", str(caught.exception))
        self.assertEqual((self.tree / "index.md.tmp").read_text(encoding="utf-8"),
                         "SOMEONE ELSE\n")

        # PAIRED POSITIVE CONTROL: with the stale tmp gone the write lands and
        # leaves no tmp behind.
        (self.tree / "index.md.tmp").unlink()
        self.mod._atomic_write_text(target, "NEW\n", contained_under=self.tree)
        self.assertEqual(target.read_text(encoding="utf-8"), "NEW\n")
        self.assertFalse((self.tree / "index.md.tmp").exists())


if __name__ == "__main__":
    unittest.main()
