# /// script
# requires-python = ">=3.11"
# dependencies = ["pyyaml>=6.0"]
# ///
"""generate-lineage.py — the vendored regenerator for docs/adrs/lineage.md.

The `link-adr-graph` skill's engine (ADR-0016), and the first conformance
instance of ADR-0056 ("every derived artifact must have a vendored regenerator
+ a drift gate"). `lineage.md` is a pure function of ADR frontmatter: a Mermaid
graph (nodes with `(superseded)` marks; solid `-->` supersedes edges; dashed
`-.->` amends edges), a lineage table, and tag clusters (tags on ≥2 ADRs).

Modes (shared crux exit-code convention):
  (no flag)   regenerate docs/adrs/lineage.md from ADR frontmatter; exit 0.
  --dry-run   the DRIFT GATE: compare on-disk lineage.md to freshly generated;
              exit 0 if byte-identical, exit 1 + unified diff on drift.
              (exit 2 = capability error, e.g. PyYAML missing.)

Deterministic + byte-stable: ADRs in ascending id order; supersedes edges then
amends edges (each in source-id order); table in id order; tag clusters
alphabetical. No timestamps in the body.
"""
from __future__ import annotations

import argparse
import difflib
import glob
import re
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.stderr.write("generate-lineage.py requires PyYAML — run via `uv run` (PEP 723 supplies it).\n")
    raise SystemExit(2)


def _tree_name(root) -> str:
    """Resolve the tree directory via bionic_config, falling back to the default."""
    _PATH = Path(__file__).resolve().parent / "bionic_config.py"
    import importlib.util as _ilu
    import sys as _sys
    _key = "_bionic_config"
    _m = _sys.modules.get(_key)
    if _m is None:
        _s = _ilu.spec_from_file_location(_key, _PATH)
        _m = _ilu.module_from_spec(_s)
        _s.loader.exec_module(_m)
        _sys.modules[_key] = _m   # cache so class identity holds across calls
    return _m.resolve_tree_name(root)


def _load_adrs(adrs_dir: Path) -> list[dict]:
    recs = []
    # Walk BOTH tiers (active + cold archive), per ADR-0063.
    both = glob.glob(str(adrs_dir / "ADR-*.md")) + glob.glob(str(adrs_dir / "archive" / "ADR-*.md"))
    for p in sorted(both):
        m = re.match(r"^---\n(.*?)\n---\n", Path(p).read_text(encoding="utf-8"), re.S)
        if not m:
            continue
        fm = yaml.safe_load(m.group(1))
        recs.append({
            "id": fm["id"],
            "num": int(str(fm["id"]).split("-")[-1]),
            "title": fm["title"],
            "status": fm["status"],
            "supersedes": fm.get("supersedes") or [],
            "amends": fm.get("amends") or [],
            "superseded_by": fm.get("superseded_by"),
            "tags": fm.get("tags") or [],
        })
    recs.sort(key=lambda r: r["num"])
    return recs


def render(recs: list[dict]) -> str:
    out: list[str] = []
    out.append("# ADR lineage\n")
    out.append("> **Regenerated by the `link-adr-graph` skill** (per [[adrs/ADR-0016-add-link-adr-graph-skill]]). Body wholly rewritten on every run; hand-edits are blown away. No timestamps in the body — byte-stable across runs given the same ADR set. See `docs/log.md` (`adr | regenerated lineage`) for when.\n")
    out.append("## Graph\n")
    out.append("Solid arrow = supersedes; dashed arrow = amends. Superseded ADRs are marked.\n")
    out.append("```mermaid")
    out.append("graph TD")
    for r in recs:
        label = f'{r["id"]} (superseded)' if r["status"] == "Superseded" else r["id"]
        out.append(f'  {r["id"].replace("-", "_")}["{label}"]')
    for r in recs:
        for tgt in r["supersedes"]:
            out.append(f'  {r["id"].replace("-", "_")} --> {tgt.replace("-", "_")}')
    for r in recs:
        for tgt in r["amends"]:
            out.append(f'  {r["id"].replace("-", "_")} -.-> {tgt.replace("-", "_")}')
    out.append("```\n")

    out.append("## Lineage table\n")
    out.append("| id | title | status | supersedes | amends | superseded_by |")
    out.append("|----|-------|--------|------------|--------|---------------|")
    for r in recs:
        sup = ", ".join(r["supersedes"]) if r["supersedes"] else "—"
        am = ", ".join(r["amends"]) if r["amends"] else "—"
        sb = r["superseded_by"] if r["superseded_by"] else "—"
        out.append(f'| {r["id"]} | {r["title"]} | {r["status"]} | {sup} | {am} | {sb} |')
    out.append("")

    out.append("## Topic clusters\n")
    out.append("ADRs grouped by shared tag (a tag appears below if ≥2 ADRs carry it). Use a cluster to find the current decision on a topic.\n")
    tagmap: dict[str, list[str]] = {}
    for r in recs:
        for t in r["tags"]:
            tagmap.setdefault(t, []).append(r["id"])
    for tag in sorted(tagmap):
        ids = tagmap[tag]
        if len(ids) >= 2:
            out.append(f'- **{tag}** — {", ".join(ids)}')
    return "\n".join(out) + "\n"


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description="Regenerate docs/adrs/lineage.md from ADR frontmatter.")
    ap.add_argument("--dry-run", action="store_true", help="drift gate: exit 1 + diff if lineage.md is stale")
    ap.add_argument("--repo-root", default=".", help="repo root (default: cwd)")
    args = ap.parse_args(argv)

    root = Path(args.repo_root)
    adrs_dir = root / _tree_name(root) / "adrs"
    target = adrs_dir / "lineage.md"
    recs = _load_adrs(adrs_dir)
    generated = render(recs)

    if args.dry_run:
        current = target.read_text(encoding="utf-8") if target.is_file() else ""
        if current == generated:
            return 0
        diff = "".join(difflib.unified_diff(
            current.splitlines(keepends=True), generated.splitlines(keepends=True),
            fromfile="docs/adrs/lineage.md (on disk)", tofile="docs/adrs/lineage.md (regenerated)"))
        sys.stdout.write("lineage.md drift — regenerate with `generate-lineage.py`:\n" + diff)
        return 1

    target.write_text(generated, encoding="utf-8")
    sys.stdout.write(f"regenerated {target} ({len(recs)} ADRs, "
                     f"{sum(len(r['supersedes']) for r in recs)} supersedes, "
                     f"{sum(len(r['amends']) for r in recs)} amends edges)\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
